sudo: required
services:
  - docker

before_install:
  - docker build -t kweiwang/docker-react -f Dockerfile.stage .
  - docker build -t kweiwang/docker-react-test -f Dockerfile.dev .

script:
  - docker run kweiwang/docker-react-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-087659596915"
  bucket-path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

