sudo: required
services:
  - docker

before_install:
  - docker build -t kweiwang/docker-react-test -f Dockerfile.dev .
  - docker build -t kweiwang/docker-react -f Dockerfile.stage .

scripts:
  - docker run kweiwang/docker-react-test npm run test -- --coverage